# Generated by Django 5.2.7 on 2025-10-20 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamenews', '0002_gallery_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='gallery',
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['uploaded_at'], 'verbose_name': 'Изображение поста', 'verbose_name_plural': 'Изображения поста'},
        ),
        migrations.AddField(
            model_name='image',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gamenews.post', verbose_name='Пост'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='post_images/', verbose_name='Изображение'),
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
